### ISSUE TITLE
Service bit filtering

### ISSUE THREAD

**Issue by cpacia** [gcash/dnsseeder#1]
Ideally we'd like to support service bit filtering. The way the dns seeders are supposed to handle this is through subdomains. For example x1.seeder.example.com should return only NODE_NETWORK nodes. 

Technically I believe you can do this with this application if you run multiple seeders on the same machine. The app supports doing so in a single instance by just passing in multiple configs via the command line at startup. 

The downside to doing it this way is it would require a new crawler and memory cache for each seeder (though I suppose the combined memory might not be much higher since the lists are filtered). 

The question is do we consider this sufficient for filtering? Or should the app supporting filtering without starting multiple crawlers? If the latter, there's a decent amount of refactoring needed to make that happen. If we don't think the overhead of multiple crawlers is that big of a deal, then I guess we're is fine as is.

**Comment by zquestz** [comment]
Honestly I think this is fine as is. There are more important items to work on and the memory footprint really isn't very big.
